version: "3.9"

services:
  property-scraper:
    image: mcr.microsoft.com/devcontainers/python:3.13-bookworm
    container_name: property-scraper
    tty: true
    stdin_open: true
    volumes:
      - .:/workspaces/property-scraper
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: /bin/bash
    build:
      context: .
      dockerfile: property-scraper/Dockerfile

